### PR TITLE
Improved Leaderboard shutdown

### PR DESCRIPTION
**Pull request by glopezdiest**
This PR focused on fixing several issues when shutting down the Leaderboard due to an error (either due to the LB itself, CARLA's server, or the agent), as it is of paramount importance that regardless of what happens, the information of the simulation is properly saved.

Some of the bugs found were:
- Watchdog: they weren't properly shutting down the simulation
- Statistics manager: Shutting down mid simulation caused some data to be missing, breaking it

Others:
- Fixed bug causing the leaderboard to crash when the route timeout was triggered
- At roads, increased the distance between points part of the stack planner to 200

- - -
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/131)

### CODE REVIEW

**Review by joel-mb — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/131)* status: all files reviewed, 1 unresolved discussion (waiting on @glopezdiest)

___
*[`scripts/scenario_creator.py` line 183 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/131#-N9pX7xv-zYceh-soeuP:-N9pX7xv-zYceh-soeuQ:bh1wf22) ([raw file](https://github.com/carla-simulator/leaderboard/blob/08baba3d42188e5f9099b15eee74319e6bd05f05/scripts/scenario_creator.py#L183)):*
> ```Python
>     "ParkingExit": [
>         ["direction", "choice"],
>         ["flow_distance", "value"],
> ```

This parameter is not used by the scenario.

**Review by glopezdiest — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/131)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @joel-mb)

___
*[`scripts/scenario_creator.py` line 183 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/131#-N9pX7xv-zYceh-soeuP:-N9pa5FP6TCxUUXjAlDg:b-896fix) ([raw file](https://github.com/carla-simulator/leaderboard/blob/08baba3d42188e5f9099b15eee74319e6bd05f05/scripts/scenario_creator.py#L183)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

This parameter is not used by the scenario.
</blockquote></details>

Done.

**Review by joel-mb — APPROVED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/131)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @joel-mb)

**Review by glopezdiest — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/131)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @glopezdiest)

**Pull request merged**
