### PR TITLE
Added live statistics

### PR DESCRIPTION
**Pull request by joel-mb**
This PR adds the possibility to visualize the statistics of the route while the stack is running.

This is the information provided:
```
Route id: ...

Scores:
    Driving score: ...
    Route completion: ...
    Infraction penalty: ...

Meta:
    Route length: ....
    Game duration: ...
    System duration: ...

Total infractions: ...
Last infractions: (shows the last 5 infractions)
    ....
```

Live results are enable when the `debug` argument is `>=1`. Live results are provided in a file called `live_results.txt`. This file is generated in the `checkpoint` folder indicated when executing the leaderboard.

Users can visualize this file in real time using the `watch` command:
```sh
watch -n 0.5 cat live_results.txt
```

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/123)

### CODE REVIEW

**Review by glopezdiest — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/123)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @glopezdiest and @joel-mb)

___
*[`leaderboard/scenarios/scenario_manager.py` line 184 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/123#-N6l0JajCtcxMAjSo9Ms:-N6l0JajCtcxMAjSo9Mt:b-dc337i) ([raw file](https://github.com/carla-simulator/leaderboard/blob/742c0b2f221d11b49d24e077e5a0b3a1f7f6f228/leaderboard/scenarios/scenario_manager.py#L184)):*
> ```Python
>             self.scenario_tree.tick_once()
> 
>             self.compute_duration_time()
> ```

This is only used by the debug on runtime? If so, put it inside the debug_mode conditional



_Code quote:_
```Python
self.compute_duration_time()
```
___
*[`leaderboard/scenarios/scenario_manager.py` line 186 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/123#-N6l0SNtDQgLBXP6xW0N:-N6l0SNtDQgLBXP6xW0O:b9e9g6o) ([raw file](https://github.com/carla-simulator/leaderboard/blob/742c0b2f221d11b49d24e077e5a0b3a1f7f6f228/leaderboard/scenarios/scenario_manager.py#L186)):*
> ```Python
>             self.compute_duration_time()
> 
>             if self._debug_mode > 0:
> ```

Right now:
- Debug = 1 shows the routes and scenario trigger
- Debug = 2 shows the py_trees 

After this, I'd do
- Debug = 1 shows the routes and scenario trigger
- Debug = 2 shows the live_results 
- Debug = 3 shows the py_trees 



_Code quote:_
```Python
if self._debug_mode > 0:
```
___
*[`leaderboard/utils/statistics_manager.py` line 323 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/123#-N6l8ZJ31QZh7en6D16_:-N6l8ZJ442zEpGKIYSLg:b-843kdc) ([raw file](https://github.com/carla-simulator/leaderboard/blob/742c0b2f221d11b49d24e077e5a0b3a1f7f6f228/leaderboard/utils/statistics_manager.py#L323)):*
> ```Python
>             'Collisions with vehicles': [],
>             'Collisions with layout': [],
>             'Red lights infractions': [],
> ```

This is very ugly, is there no other way to do this



_Code quote:_
```Python
        route_record.infractions = {
            'Collisions with pedestrians': [],
            'Collisions with vehicles': [],
            'Collisions with layout': [],
            'Red lights infractions': [],
            'Stop sign infractions': [],
            'Off-road infractions': [],
            'Min speed infractions': [],
            'Route deviations': [],
            'Route timeouts': [],
            'Agent blocked': []
        }
```
___
*[`leaderboard/utils/statistics_manager.py` line 333 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/123#-N6l91hsACbw9ihl3Vyb:-N6l91hsACbw9ihl3Vyc:b8fcd1v) ([raw file](https://github.com/carla-simulator/leaderboard/blob/742c0b2f221d11b49d24e077e5a0b3a1f7f6f228/leaderboard/utils/statistics_manager.py#L333)):*
> ```Python
> 
>         # Update the route meta
>         route_record.meta['Route length'] = round(compute_route_length(config), ROUND_DIGITS)
> ```

Recommended to calculate this at `set_scenario`, so that it's not recalculated everytime. It should algo be set to None when the scenario is removed



_Code quote:_
```Python
compute_route_length(config)
```

**Review by joel-mb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/123)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @glopezdiest)

___
*[`leaderboard/scenarios/scenario_manager.py` line 184 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/123#-N6l0JajCtcxMAjSo9Ms:-N6lN52L83mgjgfVeSP4:b-896fix) ([raw file](https://github.com/carla-simulator/leaderboard/blob/742c0b2f221d11b49d24e077e5a0b3a1f7f6f228/leaderboard/scenarios/scenario_manager.py#L184)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

This is only used by the debug on runtime? If so, put it inside the debug_mode conditional
</blockquote></details>

Done.
___
*[`leaderboard/scenarios/scenario_manager.py` line 186 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/123#-N6l0SNtDQgLBXP6xW0N:-N6lN5jpAAs3eW-1oSHu:b-896fix) ([raw file](https://github.com/carla-simulator/leaderboard/blob/742c0b2f221d11b49d24e077e5a0b3a1f7f6f228/leaderboard/scenarios/scenario_manager.py#L186)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Right now:
- Debug = 1 shows the routes and scenario trigger
- Debug = 2 shows the py_trees 

After this, I'd do
- Debug = 1 shows the routes and scenario trigger
- Debug = 2 shows the live_results 
- Debug = 3 shows the py_trees 
</blockquote></details>

Done.
___
*[`leaderboard/utils/statistics_manager.py` line 323 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/123#-N6l8ZJ31QZh7en6D16_:-N6lN7ld0AlAmE7FrcTv:b-5hwipz) ([raw file](https://github.com/carla-simulator/leaderboard/blob/742c0b2f221d11b49d24e077e5a0b3a1f7f6f228/leaderboard/utils/statistics_manager.py#L323)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

This is very ugly, is there no other way to do this
</blockquote></details>

Infractions dictionary is now updated using the `PENALTY_NAME_DICT` values.
___
*[`leaderboard/utils/statistics_manager.py` line 333 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/123#-N6l91hsACbw9ihl3Vyb:-N6lNJYM1FX1OMko6mS6:b-896fix) ([raw file](https://github.com/carla-simulator/leaderboard/blob/742c0b2f221d11b49d24e077e5a0b3a1f7f6f228/leaderboard/utils/statistics_manager.py#L333)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Recommended to calculate this at `set_scenario`, so that it's not recalculated everytime. It should algo be set to None when the scenario is removed
</blockquote></details>

Done.

**Review by glopezdiest — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/123)* status: all files reviewed, 1 unresolved discussion (waiting on @joel-mb)

___
*[`leaderboard/leaderboard_evaluator.py` line 365 at r2](https://reviewable.io/reviews/carla-simulator/leaderboard/123#-N6lP5rrDkRk-0Q2Vi0P:-N6lP5rs-z4yKudwMxBM:b-rzy4oc) ([raw file](https://github.com/carla-simulator/leaderboard/blob/8956a8d967107b2ad1d1f1c68bdc571759434a62/leaderboard/leaderboard_evaluator.py#L365)):*
> ```Python
>         print("\033[1m> Registering the global statistics\033[0m")
>         self.statistics_manager.compute_global_statistics()
>         self.statistics_manager.validate_statistics()
> ```

I'd change this to a single function such as `validate_and_write_statistics`



_Code quote:_
```Python
        self.statistics_manager.validate_statistics()
        self.statistics_manager.write()
```

**Review by joel-mb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/123)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @glopezdiest)

___
*[`leaderboard/leaderboard_evaluator.py` line 365 at r2](https://reviewable.io/reviews/carla-simulator/leaderboard/123#-N6lP5rrDkRk-0Q2Vi0P:-N6lTGFHDS61skK_v1Vr:b-896fix) ([raw file](https://github.com/carla-simulator/leaderboard/blob/8956a8d967107b2ad1d1f1c68bdc571759434a62/leaderboard/leaderboard_evaluator.py#L365)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

I'd change this to a single function such as `validate_and_write_statistics`
</blockquote></details>

Done.

**Review by glopezdiest — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/123)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @joel-mb)

**Pull request merged**
