### PR TITLE
Remove deprecation warnings for version checking in 3.8 & 3.10+ (2.7 backward compatible)

### PR DESCRIPTION
**Pull request by Daraan**
Removes two deprecation warnings that come up in newer python version:
- distutils will be removed in Python3.12, and marked as deprecated in 3.10 [PEP 632](https://peps.python.org/pep-0632/)
- pkg_version, should not be used in newer versions of setuptools https://setuptools.pypa.io/en/latest/pkg_resources.html

This PR can still be used with older Python version that do not provide the new modules.

- - -
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/172)

### CODE REVIEW

**Comment by Daraan** [comment]
It might also be nicer to move the version stuff into an extra file in utils or so. `from utils import get_carla_version` and have the try...except blocks there or use a different approach.

**Comment by PabloVD** [comment]
Thanks for the PR. Could you please do the PR to the master branch and change the minimum version to 0.9.15, which is the default version used in Leaderboard 2?

**Comment by Daraan** [comment]
@PabloVD 

> Thanks for the PR. Could you please do the PR to the master branch and change the minimum version to 0.9.15, which is the default version used in Leaderboard 2?

@PabloVD . Changed to master and 0.9.15

**Review by PabloVD — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/172)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @glopezdiest and @joel-mb)

**Pull request merged**
