### PR TITLE
Add distortion and andvanced camera parameters

### PR DESCRIPTION
**Pull request by Sid1057**
in agent_wrapper sensor specification

In the case of using stereo cameras or some classic CV-algorithms, developers can be able to adjust the distortion parameters, etc.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/47)

### CODE REVIEW

**Comment by germanros1987** [comment]
Hi @Sid1057 ,

Thanks for your PR. This contribution makes sense in general. However, in the context of the CARLA leaderboard, I want these parameters to be specified by the system and not tunable by the user. This is done so that all agents have to use the same type of sensor configuration.

**Comment by Sid1057** [comment]
@germanros1987  thank you for the answer.

Ok, but could you please add an example of image undistortion using OpenCV in the documentation instead this PR? Converting the lens parameters specified through UE4 to the OpenCV distortion coefficient format is not obvious, but it is very important for building an self-driving system. And for me, for example, it was faster and easier to change the agent code regarding lens distortion than correctly interpreting them for the cv.undistort function.

**Comment by germanros1987** [comment]
Hi @Sid1057 

Shouldn't the undirstortion algorithm be independent from the parameters that we set in our sensors? In other words, our sensors are black-boxes that distort the image through several functions. Now, it is up to the user to find a way to rectify these images from the data (images) themselves. 

Perhaps, what is really missing in CARLA is a calibration board prop, so that you can run calibration methods out-of-the-box.

**Comment by Sid1057** [comment]
Hi @germanros1987 

The ability to use the calibration board in the simulator will be enough to close this question. But while this functionality does not exist, developers who want to try their own autonomous vehicle algorithms should focus on the auto-calibration task, which in the case of cameras is really complicated and should be presented as a separate track.
Another argument for providing intrinsic parameters to developers is the similarity of using the simulator with open datasets (such as KITTI, a2d2, etc. where parameters are predefined) and the process of developing self-driving cars, where most teams can select sensors and calculate their parameters at the stage of preparing the transport (using various calibration methods, including using a chessboard).

**Pull request closed without merging**
