### PR TITLE
Integration ROS/ROS2 agents

### PR DESCRIPTION
**Pull request by joel-mb**
This PR adds beta support for the usage of ROS1/ROS2 agents in the leaderboard. Currently, the supported ROS versions are:
* ROS1 melodic
* ROS1 noetic
* ROS2 foxy

The integration uses the CARLA ROS bridge package to manage the creation/destruction of sensors and the sensor data publication. 

#### Code structure
* *ROSBaseAgent*: This is the base ROS agent. User should **not** inherit from this class. This base agent contains shared functionality between ROS1 and ROS2 agents.
* *ROS1Agent*: ROS1 agents should inherit from this class. It uses `roslibpy` and `rosbridge-server` to communicate with the ROS environment.
* *ROS2Agent*: ROS2 agents should inherit from this class. It creates a node using `rclpy` to communicate with the ROS environment. 

* *ROSAgentWrapper*: Agent wrapper for ROS agents. This wrapper is responsible for calling the `/carla/spawn_object` and `/carla/destroy_object` ROS services to spawn/destroy the agent sensors. 

Additionally, the scenario/agent setup code has been reorganized to avoid ticking the CARLA server once the agent is initialized.

#### Dockerfile

A new dockerfile (`Dockerfile.ros`) has been provided to build ROS based images. Also, the `make_docker.sh` has been updated to this end. To create a ROS based image use:
```sh
./make_docker.sh --ros-distro melodic
```
with the desired ROS distribution. If no distribution is provided, the "normal" pipeline is applied.

### Team code
For ROS agents, it is assumed that the team code root folder is a ROS workspace containing all the necessary packages.
```
<TEAM_CODE_ROOT>
|__ src
    |__ pakcage1
    |__ package2
    |__ ...
```

Additionally, ROS agents must provide a ROS entry point to executed the agent.

```py
class MyRosAgent(ROS1Agent):
    ....
    def get_ros_entry_point(self):
        return {
            "package": "my_ros_agent",
            "launch_file": "my_ros_agent.launch",
            "parameters": {}
        }
```

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/85)

### CODE REVIEW

**Review by glopezdiest — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/85)* status: all files reviewed, 3 unresolved discussions (waiting on @fpasch and @joel-mb)

___
*[leaderboard/autoagents/agent_wrapper.py, line 22 at r2](https://reviewable.io/reviews/carla-simulator/leaderboard/85#-MXlqieW6EoBmloeco8V:-MXlqieW6EoBmloeco8W:b-h3c5pn) ([raw file](https://github.com/carla-simulator/leaderboard/blob/43f346199962d00d41a9484099610dd52c1611d8/leaderboard/autoagents/agent_wrapper.py#L22)):*
> ```
> from leaderboard.autoagents.ros_base_agent import ROSBaseAgent
> ```
This brings new dependencies even to non ROS users. Maybe check the ROS_VERSION var at the ROS agents? If not, add them at the requirements.txt
___
*[leaderboard/autoagents/agent_wrapper.py, line 100 at r2](https://reviewable.io/reviews/carla-simulator/leaderboard/85#-MXlrFHq40cPaOPe5t2d:-MXlrFHq40cPaOPe5t2e:b-8tc0a7) ([raw file](https://github.com/carla-simulator/leaderboard/blob/43f346199962d00d41a9484099610dd52c1611d8/leaderboard/autoagents/agent_wrapper.py#L100)):*
> ```
> frame_rate'
> ```
change this to `reading_frequency`, same as the opendrive
___
*[leaderboard/autoagents/autonomous_agent.py, line 36 at r2](https://reviewable.io/reviews/carla-simulator/leaderboard/85#-MXlrcaZ-ICKo_7ggi1S:-MXlrcaZ-ICKo_7ggi1T:bkiyc5e) ([raw file](https://github.com/carla-simulator/leaderboard/blob/43f346199962d00d41a9484099610dd52c1611d8/leaderboard/autoagents/autonomous_agent.py#L36)):*
> ```
> debug=False
> ```
This isn't used anywhere?

**Comment by hatem-darweesh** [comment]
Hello, 
I have some questions: 
Q1: 
- when using ros, I export the 2.7 carla egg , then I have to modify the run_evaluator.sh 
- I replace python3 with python2 , otherwise it crashes , **when submitting my docker file, will that be a problem ?**

Q2: 
- ros_base_agent and ros1_agent initializes and uses carla_ros_bridge, **what if I don't want to use carla_ros_bridge at all** 

Q3: 
- I would like an agent example such as ros_agent.py , that enables ROS1 and Python 2.7, and runs the team_agent using the "start.sh" file. 

Comment: Related to the LIDAR reading frequency. 
- rotation_frequency of the sensor is "10" by default. and points_per_second is "600000" 
- when data is read at 20hz, only half scan is returned. 
- I fixed this by increasing rotation_frequency to "20" and points_per_second to "1200000"

if you want to check my modifications: 

https://github.com/hatem-darweesh/leaderboard

Regards,

**Comment by joel-mb** [comment]
Hi @hatem-darweesh ,
Thank you for the feedback!

> Q1:
>    * when using ros, I export the 2.7 carla egg , then I have to modify the run_evaluator.sh
>    * I replace python3 with python2 , otherwise it crashes , when submitting my docker file, will that be a problem ?

The leaderboard is only targeting Python3. Even if you modify the leaderboard, it will be replaced with the original one once it is submitted. Therefore, your original issue will appear on the cloud, even if you upload a docker image with a modified version of the leaderboard.

In order to support agents based on ROS melodic (which is targeting Python2), the current ROS-leaderboard integration is using `roslibpy` for ROS1 based agents. This library allows to interact with ROS without requiring the creation of a specific ROS node and therefore avoid the Python2-Python3 problem.

ROS melodic based agents can still be programmed normally using Python2. Moreover, the CARLA PythonAPI is available for Python2 and Python3 in the resulting Docker image (https://github.com/carla-simulator/leaderboard/blob/glopez/initialization_reordered/scripts/Dockerfile.ros#L97)

> Q2:
>   * ros_base_agent and ros1_agent initializes and uses carla_ros_bridge, what if I don't want to use carla_ros_bridge at all

I would like to receive some more feedback about this. In which situations you would want to avoid the usage of the CARLA ROS bridge? In the end, the CARLA ROS bridge is doing nothing but publishing the sensor data and managing the creation and destruction of sensors.

> Q3:
>   * I would like an agent example such as ros_agent.py , that enables ROS1 and Python 2.7, and runs the team_agent using the "start.sh" file.

The way to execute ROS based agents on the ledearboard has slightly changed. Here you can see a dummy agent for the leaderboard using ROS melodic: https://github.com/joel-mb/leaderboard-ros-agent

> Comment: Related to the LIDAR reading frequency.
>
>    rotation_frequency of the sensor is "10" by default. and points_per_second is "600000"
>    when data is read at 20hz, only half scan is returned.
>    I fixed this by increasing rotation_frequency to "20" and points_per_second to "1200000"

Yes. This is already known and these values are fixed for the leaderboard.

**Comment by hatem-darweesh** [comment]
Thanks @joel-mb , 
That was really helpful. 
I tried the dummy agent, and I get the system to work. still need to source my ros agent correctly. but no python issues :) 

I will wait until this PR is accepted and will submit my agent. 

Thanks again,

**Comment by joel-mb** [comment]
@hatem-darweesh thanks again for the feeback!

> still need to source my ros agent correctly. but no python issues :)
How are you building your image? Are you using the provided `Dockerfile.ros` file as a template (https://github.com/carla-simulator/leaderboard/blob/glopez/initialization_reordered/scripts/Dockerfile.ros)? The sourcing should be done automatically, assuming that the team code root folder is a ROS workspace containing all the necessary packages. So for the `dummy_agent` the team code root folder should be something like:

```
<TEAM_CODE_ROOT>
|__ my_ros_agent.py
|__ src
    |__ dummy_agent
        |__ ...
```
And your `TEAM_AGENT` variable `${TEAM_CODE_ROOT}/my_ros_agent.py`

We still need to properly document this.

**Review by joel-mb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/85)* status: 11 of 15 files reviewed, 3 unresolved discussions (waiting on @fpasch and @glopezdiest)

___
*[leaderboard/autoagents/agent_wrapper.py, line 22 at r2](https://reviewable.io/reviews/carla-simulator/leaderboard/85#-MXlqieW6EoBmloeco8V:-MYnoOcK3g_eGks8PEiZ:b-ftia97) ([raw file](https://github.com/carla-simulator/leaderboard/blob/43f346199962d00d41a9484099610dd52c1611d8/leaderboard/autoagents/agent_wrapper.py#L22)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> from leaderboard.autoagents.ros_base_agent import ROSBaseAgent
> ```
This brings new dependencies even to non ROS users. Maybe check the ROS_VERSION var at the ROS agents? If not, add them at the requirements.txt
</blockquote></details>

Done. Added new dependencies to `requirements.txt`
___
*[leaderboard/autoagents/agent_wrapper.py, line 100 at r2](https://reviewable.io/reviews/carla-simulator/leaderboard/85#-MXlrFHq40cPaOPe5t2d:-MYnoYGu1dFK_DXllSRh:b-896fix) ([raw file](https://github.com/carla-simulator/leaderboard/blob/43f346199962d00d41a9484099610dd52c1611d8/leaderboard/autoagents/agent_wrapper.py#L100)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> frame_rate'
> ```
change this to `reading_frequency`, same as the opendrive
</blockquote></details>

Done.
___
*[leaderboard/autoagents/autonomous_agent.py, line 36 at r2](https://reviewable.io/reviews/carla-simulator/leaderboard/85#-MXlrcaZ-ICKo_7ggi1S:-MYnoaJrBMph4IKj8bBl:b-896fix) ([raw file](https://github.com/carla-simulator/leaderboard/blob/43f346199962d00d41a9484099610dd52c1611d8/leaderboard/autoagents/autonomous_agent.py#L36)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> debug=False
> ```
This isn't used anywhere?
</blockquote></details>

Done.

**Review by glopezdiest — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @fpasch)

**Pull request merged**
