### PR TITLE
Integration ROS/ROS2 agents

### PR DESCRIPTION
**Pull request by joel-mb**
This PR adds beta support for the usage of ROS1/ROS2 agents in the leaderboard. Currently, the supported ROS versions are:
* ROS1 melodic
* ROS1 noetic
* ROS2 foxy

The integration uses the CARLA ROS bridge package to manage the creation/destruction of sensors and the sensor data publication. 

### Design
The integration is designed to work synchronously. By default, the leaderboard wait until a new vehicle command with the timestamp of the current frame is received. Vehicle commands with a repeated or old timestamp are ignored.

This behavior can be changed by the user overriding the `ROSBaseAgent._vehicle_control_cmd_callback`. **When overriding the default behavior, the user is responsible for deciding which vehicle command is applied in each step**.

### Code structure
* *ROSBaseAgent*: This is the base ROS agent. User should **not** inherit from this class. This base agent contains shared functionality between ROS1 and ROS2 agents.
* *ROS1Agent*: ROS1 agents should inherit from this class. It uses `roslibpy` and `rosbridge-server` to communicate with the ROS environment.
* *ROS2Agent*: ROS2 agents should inherit from this class. It creates a node using `rclpy` to communicate with the ROS environment. 

* *ROSAgentWrapper*: Agent wrapper for ROS agents. This wrapper is responsible for calling the `/carla/spawn_object` and `/carla/destroy_object` ROS services to spawn/destroy the agent sensors. 

Additionally, the scenario/agent setup and destruction code has been reorganized to avoid ticking the CARLA server once the agent is initialized.

### Team code
For ROS agents, it is assumed that the team code root folder is a ROS workspace containing all the necessary packages.
```
<TEAM_CODE_ROOT>
|__ src
    |__ pakcage1
    |__ package2
    |__ ...
```

Additionally, ROS agents must provide a ROS entry point to executed the agent.

```py
class MyRosAgent(ROS1Agent):
    ....
    def get_ros_entry_point(self):
        return {
            "package": "my_ros_agent",
            "launch_file": "my_ros_agent.launch",
            "parameters": {}
        }
```

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/94)

### CODE REVIEW

**Review by glopezdiest — COMMENTED** [review]
> Reviewed 9 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/94)* status: 9 of 16 files reviewed, 13 unresolved discussions (waiting on @joel-mb)

___
*[leaderboard/autoagents/agent_wrapper.py, line 181 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eH9Ao5kwYwWz7CW4e:-M_eH9Ao5kwYwWz7CW4f:b-vycg9o) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/agent_wrapper.py#L181)):*
> ```
> debug_mode=False
> ```
Unused
___
*[leaderboard/autoagents/agent_wrapper.py, line 194 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eEnnk6wUftwyW1FbK:-M_eEnnk6wUftwyW1FbL:b-u1e8bu) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/agent_wrapper.py#L194)):*
> ```
> sensor_spec['type']
> ```
this should be `type_`
___
*[leaderboard/autoagents/agent_wrapper.py, line 205 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eF80I1C-ByJQKNVf6:-M_eF80I1C-ByJQKNVf7:b99e4e0) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/agent_wrapper.py#L205)):*
> ```
> sensor_spec['id']
> ```
id_
___
*[leaderboard/autoagents/agent_wrapper.py, line 205 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eF96T7ZlAlmNJNLuX:-M_eF96T7ZlAlmNJNLuY:b-eifeug) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/agent_wrapper.py#L205)):*
> ```
> sensor_spec['type']
> ```
type_
___
*[leaderboard/autoagents/agent_wrapper.py, line 212 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eGA8G5xlkKBXdbYcT:-M_eGA8G5xlkKBXdbYcU:b-9tvf0f) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/agent_wrapper.py#L212)):*
> ```
>  validate_sensor_configuration
> ```
This might be better if its outside the AgentWrapper now, two avoid confusion the two AgentWrappers
___
*[leaderboard/autoagents/agent_wrapper.py, line 292 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eH4USAXJ0etdrzBQh:-M_eH4USAXJ0etdrzBQi:b-vycg9o) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/agent_wrapper.py#L292)):*
> ```
> debug_mode=False
> ```
Unused
___
*[leaderboard/autoagents/agent_wrapper.py, line 305 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eK4u45tgRoPrizOEm:-M_eK4u45tgRoPrizOEn:b-w9ejze) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/agent_wrapper.py#L305)):*
> ```
> #self._agent._step_once_service.call(roslibpy.ServiceRequest({"command": 2}))
> ```
remove
___
*[leaderboard/autoagents/agent_wrapper.py, line 314 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eK6Ux9R66IHVmuQb8:-M_eK6Ux9R66IHVmuQb9:bgas1bm) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/agent_wrapper.py#L314)):*
> ```
> #self._agent._step_once_service.call(roslibpy.ServiceRequest({"command": 2}))
> ```
remove + add end of file line
___
*[leaderboard/autoagents/ros1_agent.py, line 114 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eJQue-RWqBMcPu5uD:-M_eJQue-RWqBMcPu5uE:b1ibvya) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/ros1_agent.py#L114)):*
> ```
> # TODO: raise error when a error ocurred (i.e. response["id"] == -1)?
> ```
Definitely do that, if the sensor didn't get spawned, raise an error, the leaderboard evaluator will catch it no problem
___
*[leaderboard/autoagents/ros2_agent.py, line 95 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eJorEAcotavm8zUX9:-M_eJorEAcotavm8zUXA:b-jbjiyv) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/ros2_agent.py#L95)):*
> ```
>         # Call the service synchornously.
>         response = self._spawn_object_service.call(request)
> ```
typo + Ros1Agent has a TODO to do an error check. Here too 
___
*[leaderboard/autoagents/ros_base_agent.py, line 110 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eIW9G2SDf7cuXW81C:-M_eIW9G2SDf7cuXW81D:b-s9h9ai) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/ros_base_agent.py#L110)):*
> ```
> def carla2ros_pose(cls, x, y, z, roll, pitch, yaw, to_quat=False):
> ```
Why not directly pass the transform?
___
*[leaderboard/autoagents/ros_base_agent.py, line 123 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eIzY28VSX6CICsSCs:-M_eIzY28VSX6CICsSCt:b6vpvru) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/ros_base_agent.py#L123)):*
> ```
> def rpy2quat(roll, pitch, yaw):
> ```
Same here, pass the rotation instead of rpy?
___
*[leaderboard/envs/sensor_interface.py, line 201 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eL0n_8lWjiGYgrM_g:-M_eL0n_8lWjiGYgrM_h:b3qkhip) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/envs/sensor_interface.py#L201)):*
> ```
> self._new_data_buffers = Queue()
> ```
Rename it to `self._data_buffers`, instead of deleting the old name

**Comment by glopezdiest** [comment]
Here are some comments. This is just part 1 of the static code review. I'll next check the ros agents and then I'll try to do dynamic analysis

**Review by glopezdiest — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/94)* status: 9 of 16 files reviewed, 15 unresolved discussions (waiting on @joel-mb)

___
*[leaderboard/autoagents/ros1_agent.py, line 94 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_fJtD_7IWiH5Y_3sGe:-M_fJtD_7IWiH5Y_3sGf:bz8bpvr) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/ros1_agent.py#L94)):*
> ```
> status
> ```
Unused
___
*[leaderboard/autoagents/ros2_agent.py, line 73 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_fKTy4EzYuLCDr1NIO:-M_fKTy4EzYuLCDr1NIP:bz8bpvr) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/ros2_agent.py#L73)):*
> ```
> status
> ```
Unused

**Review by glopezdiest — COMMENTED** [review]
> Reviewed 7 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/94)* status: all files reviewed, 15 unresolved discussions (waiting on @joel-mb)

**Review by joel-mb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/94)* status: 9 of 16 files reviewed, 15 unresolved discussions (waiting on @glopezdiest and @joel-mb)

___
*[leaderboard/autoagents/agent_wrapper.py, line 181 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eH9Ao5kwYwWz7CW4e:-Ma4AciLERro693_Iqql:b-896fix) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/agent_wrapper.py#L181)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> debug_mode=False
> ```
Unused
</blockquote></details>

Done.
___
*[leaderboard/autoagents/agent_wrapper.py, line 194 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eEnnk6wUftwyW1FbK:-Ma4AdO0Affq2BbwE8CY:b-896fix) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/agent_wrapper.py#L194)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> sensor_spec['type']
> ```
this should be `type_`
</blockquote></details>

Done.
___
*[leaderboard/autoagents/agent_wrapper.py, line 205 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eF80I1C-ByJQKNVf6:-Ma4Ae0O-kXyd4E1XM5k:b-896fix) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/agent_wrapper.py#L205)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> sensor_spec['id']
> ```
id_
</blockquote></details>

Done.
___
*[leaderboard/autoagents/agent_wrapper.py, line 205 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eF96T7ZlAlmNJNLuX:-Ma4AeI-ASB7hp-YWXJt:b-896fix) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/agent_wrapper.py#L205)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> sensor_spec['type']
> ```
type_
</blockquote></details>

Done.
___
*[leaderboard/autoagents/agent_wrapper.py, line 212 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eGA8G5xlkKBXdbYcT:-Ma4AeyR9adFgbqqniJD:b-896fix) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/agent_wrapper.py#L212)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
>  validate_sensor_configuration
> ```
This might be better if its outside the AgentWrapper now, two avoid confusion the two AgentWrappers
</blockquote></details>

Done.
___
*[leaderboard/autoagents/agent_wrapper.py, line 292 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eH4USAXJ0etdrzBQh:-Ma4Afdy0S6mTHrwy5hl:b-896fix) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/agent_wrapper.py#L292)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> debug_mode=False
> ```
Unused
</blockquote></details>

Done.
___
*[leaderboard/autoagents/agent_wrapper.py, line 305 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eK4u45tgRoPrizOEm:-Ma4Agki9ScoIqpUOIQc:b-896fix) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/agent_wrapper.py#L305)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> #self._agent._step_once_service.call(roslibpy.ServiceRequest({"command": 2}))
> ```
remove
</blockquote></details>

Done.
___
*[leaderboard/autoagents/agent_wrapper.py, line 314 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eK6Ux9R66IHVmuQb8:-Ma4AhbV4XeC2pdzup90:b-896fix) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/agent_wrapper.py#L314)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> #self._agent._step_once_service.call(roslibpy.ServiceRequest({"command": 2}))
> ```
remove + add end of file line
</blockquote></details>

Done.
___
*[leaderboard/autoagents/ros1_agent.py, line 94 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_fJtD_7IWiH5Y_3sGe:-Ma4Ajp48FIeza6RB-43:b-896fix) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/ros1_agent.py#L94)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> status
> ```
Unused
</blockquote></details>

Done.
___
*[leaderboard/autoagents/ros1_agent.py, line 114 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eJQue-RWqBMcPu5uD:-Ma4AlUsA9EXnkIIQooQ:b-896fix) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/ros1_agent.py#L114)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> # TODO: raise error when a error ocurred (i.e. response["id"] == -1)?
> ```
Definitely do that, if the sensor didn't get spawned, raise an error, the leaderboard evaluator will catch it no problem
</blockquote></details>

Done.
___
*[leaderboard/autoagents/ros2_agent.py, line 73 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_fKTy4EzYuLCDr1NIO:-Ma4Amyd8Ch7gXmhsXww:b-896fix) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/ros2_agent.py#L73)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> status
> ```
Unused
</blockquote></details>

Done.
___
*[leaderboard/autoagents/ros2_agent.py, line 95 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eJorEAcotavm8zUX9:-Ma4Ank-BPEOXIqcxCXM:b-896fix) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/ros2_agent.py#L95)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
>         # Call the service synchornously.
>         response = self._spawn_object_service.call(request)
> ```
typo + Ros1Agent has a TODO to do an error check. Here too 
</blockquote></details>

Done.
___
*[leaderboard/envs/sensor_interface.py, line 201 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eL0n_8lWjiGYgrM_g:-Ma4AqjV7n9lGr5fZiBK:b-896fix) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/envs/sensor_interface.py#L201)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> self._new_data_buffers = Queue()
> ```
Rename it to `self._data_buffers`, instead of deleting the old name
</blockquote></details>

Done.

**Review by glopezdiest — COMMENTED** [review]
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/94)* status: all files reviewed, 4 unresolved discussions (waiting on @joel-mb)

___
*[leaderboard/autoagents/ros1_agent.py, line 114 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eJQue-RWqBMcPu5uD:-Ma8gM3n1QhktQJcBVh6:bp0flhe) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/ros1_agent.py#L114)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Chacnges look good. However (and I didn't think about this before), this might need some more tuning, as this wouldn't be an error caused by the agent, but the simulation instead, which might need to be separated. I'll check it in detail
___
*[leaderboard/autoagents/ros2_agent.py, line 95 at r1](https://reviewable.io/reviews/carla-simulator/leaderboard/94#-M_eJorEAcotavm8zUX9:-Ma8ghjtEYFGNBvgLTUg:bbopghl) ([raw file](https://github.com/carla-simulator/leaderboard/blob/ca721d6818cf01b008f2b0233894beae7d7c0055/leaderboard/autoagents/ros2_agent.py#L95)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Same problem as before, will also check it

**Review by glopezdiest — APPROVED** [review]
> Reviewed 2 of 4 files at r3, 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/leaderboard/94)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @joel-mb)

**Pull request merged**
